<?xml version="1.0" encoding="utf-8"?><Database Name="TestDB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.1.10.114,1434;Initial Catalog=TestDB;Persist Security Info=True;User ID=ugoadmin" SettingsObjectName="Alfred.Properties.Settings" SettingsPropertyName="TestDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustID" Type="System.Decimal" DbType="Decimal(9,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CustName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <!--<Column Name="Created" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />-->
      <Column Name="LastSeen" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="TotalNoOfOrders" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <!--<Column Name="BasketSum" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />-->
      <Column Name="BasketAvg" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <!--<Column Name="PriceSum" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />-->
      <Column Name="PriceAvg" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CustStatus" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>